### ISSUE TITLE
Footer issue

### ISSUE THREAD

**Issue by isaacmeira** [vmarcosp/minimalist-profile#12]
Hello, i found another issue on responsive mode
on 375 x 667 resolution in my iphone 6 device

![issue](https://user-images.githubusercontent.com/43460570/45929316-4578b080-bf26-11e8-8883-1f74418950ce.png)
the fonts at the end of the code is totally out of context, could be a bit smaller, and also adjusted to the same size

**Comment by luanraithz** [comment]
Hi @isaacmeira, I've made some changes in this project today, can you test it and see if it solves your problem? It this deployed [here](https://luanraithz.netlify.com/)

**Comment by luanraithz** [comment]
Oh, btw, I've also changed the header and image profile size, check it out too.

**Comment by isaacmeira** [comment]
Looks better now, btw , congrats for your work ;)

**Comment by luanraithz** [comment]
Fixed in #13 .
