### ISSUE TITLE
Install google fonts on <link> instead of @import

### ISSUE THREAD

**Issue by VitorLuizC** [vmarcosp/minimalist-profile#3]
Use a `<link rel="stylesheet">` on `index.html` instead of this

https://github.com/vmarcosp/minimalist-profile/blob/3dd569e2844c932f6b8a26d4411fc60d2376cedd/scss/all.scss#L1

CSS `@import` inside an file imported with a `<link rel="stylesheet">` cause browsers to download each file in sequence. Download font and style as `<link rel="stylesheet">` cause browsers to download files in parallel which is much better!

[Source](http://www.stevesouders.com/blog/2009/04/09/dont-use-import/)

**Comment by vmarcosp** [comment]
Yes I did it temporarily :smile: . That was already on my list of improvements.

**Comment by vmarcosp** [comment]
Fix in [this](https://github.com/vmarcosp/minimalist-profile/commit/2e9cd6296cc7a3509b555c177a650aba4930d0d1) changes.
