### ISSUE TITLE
Add EditorConfig/GitAttributes to keep line-endings and indentation consistent

### ISSUE THREAD

**Issue by VitorLuizC** [vmarcosp/minimalist-profile#5]
Looking ahead, this project will grow and contributors can use any OS and editor. This will cause some inconsistencies on line-ends (Windows CRLF / Unix LF) and indentation (tab / space), so an `.editorconfig` file and a `.gitattributes` could define settings to prevent it.

**Comment by vmarcosp** [comment]
Thanks for your suggestion 😄. Created in [this](https://github.com/vmarcosp/minimalist-profile/commit/e3193bdae58ad64683c7322e1de955b171927ad6)
